"""Alerte model — automatic notifications generated by thresholds or IA."""
from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, DateTime
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


class Alerte(Base):
    __tablename__ = "alertes"

    id = Column(Integer, primary_key=True)
    etudiant_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    type = Column(String(50), nullable=False)  # absence, note, ia_risque
    urgence = Column(String(20), default="info", nullable=False)  # info, warning, critical
    titre = Column(String(200), nullable=False)
    message = Column(String(1000), nullable=False)
    lue = Column(Boolean, default=False, nullable=False, index=True)

    score_risque = Column(Integer, nullable=True)  # if IA-generated
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    etudiant = relationship("User", foreign_keys=[etudiant_id], back_populates="alertes")
